version: '3.7'

services:
  database: 
    image: postgres
    container_name: database_traveller
    restart: always
    ports:
      - 5454:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=base
      - POSTGRES_DB=traveller
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: traveller
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links: 
      - database
    depends_on: 
      - database

volumes:
  pgdata:
    driver: local